name: pretest2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  flutter_native_splash: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

flutter_native_splash:
  color: '#800080'
  image: assets/images/foto.jpeg
  color_dark: '#121212'
  image_dark: assets/images/foto.jpeg
  android_12:
    image: assets/images/foto.jpeg
    icon_background_color: '#ffffff'
    image_dark: assets/images/foto.jpeg
    icon_background_color_dark: '#121212'
  web: false
