// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhjG_xpEb6e3lY8PbQW7jHGQxhokQhSjw',
    appId: '1:913006811009:web:6c13134657cfa82f23ba80',
    messagingSenderId: '913006811009',
    projectId: 'pretest2-2ea51',
    authDomain: 'pretest2-2ea51.firebaseapp.com',
    storageBucket: 'pretest2-2ea51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsjeuVnTK0rPtkqvJvbQNA6vs7jqBgCc8',
    appId: '1:913006811009:android:a2ead5e227ebf0db23ba80',
    messagingSenderId: '913006811009',
    projectId: 'pretest2-2ea51',
    storageBucket: 'pretest2-2ea51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoETCULWoNAFgj7BvEEWvYiq0k-v-Corg',
    appId: '1:913006811009:ios:cad95cd17478d29c23ba80',
    messagingSenderId: '913006811009',
    projectId: 'pretest2-2ea51',
    storageBucket: 'pretest2-2ea51.firebasestorage.app',
    iosBundleId: 'com.example.pretest2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoETCULWoNAFgj7BvEEWvYiq0k-v-Corg',
    appId: '1:913006811009:ios:cad95cd17478d29c23ba80',
    messagingSenderId: '913006811009',
    projectId: 'pretest2-2ea51',
    storageBucket: 'pretest2-2ea51.firebasestorage.app',
    iosBundleId: 'com.example.pretest2',
  );
}
